# Site settings
title: Joanne Zhou
description: Joanne's personal website
baseurl: "/will-jekyll-template" # the subpath of your site, e.g. /blog
url: "https://jwnzhou.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Joanne Zhou
user_description: Junior Product Manager at MealSuite
user_title: Dietitian, Product Management Professional
email: treegreen.jiz@gmail.com
twitter_username: jwnzhou
github_username:  jwnzhou
# gplus_username:  lorem_ipsum
# disqus_username: lorem_ipsum

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
